### ISSUE TITLE
Improve the speed

### ISSUE THREAD

**Issue by shawaiz-khan** [shawaiz-khan/shawaizkhan-portfolio#2]
I want my site to be improved in speed

**Comment by PAVAN507-STAR** [comment]
Hii @shawaiz-khan I would like to work on this

**Comment by shawaiz-khan** [comment]
> Hii @shawaiz-khan I would like to work on this

Okay go on

**Comment by shawaiz-khan** [comment]
> Hii @shawaiz-khan I would like to work on this

Create a new beach in the forked repo and then create a pr when done.

**Comment by PAVAN507-STAR** [comment]
@shawaiz-khan  can u tell me what i need to do exactly ,because nothing on your website looks slow to me
